import { chromium } from "playwright";
import fs from "fs";
import path from "path";

// Get XML path from command line arguments
const XML_PATH = process.argv[2];
const OUTPUT_DIR = process.argv[3];

if (!XML_PATH || !OUTPUT_DIR) {
  console.error("Usage: node runner_execute.js <xml_path> <output_dir>");
  process.exit(1);
}

(async () => {
  try {
    // Load XML generated by compiler
    const xmlText = fs.readFileSync(XML_PATH, "utf-8");

    console.log(`🔄 Executing XML: ${XML_PATH}`);

    const browser = await chromium.launch({ headless: true }); // Run headless for automation
    const page = await browser.newPage();

    // Open CodeAsthram
    await page.goto("https://hackpy.tarcin.in/");
    await page.waitForTimeout(6000); // Blockly load delay

    // Inject execution helper
    await page.addScriptTag({
      path: path.resolve("./execute_xml.js")
    });

    // Execute XML in browser
    const result = await page.evaluate(
      xml => window.executeXML(xml),
      xmlText
    );

    console.log("📊 Execution result:", result.status);

    // Ensure output directory exists
    fs.mkdirSync(OUTPUT_DIR, { recursive: true });

    // Save outputs
    const xmlOutputPath = path.join(OUTPUT_DIR, "result.xml");
    const txtOutputPath = path.join(OUTPUT_DIR, "result.txt");

    fs.writeFileSync(xmlOutputPath, xmlText);
    fs.writeFileSync(txtOutputPath, result.python || "");

    // Handle diagnostics
    let diagnostics = "";
    if (result.status !== "success") {
      diagnostics = `Execution failed: ${result.status}\nError: ${result.error || "Unknown error"}\n`;
      console.log(`❌ Execution failed: ${result.status}`);
    } else {
      diagnostics = "Execution successful\n";
      console.log(`✅ Execution successful - Generated ${result.python.length} characters of Python code`);
    }

    await browser.close();

    // Write diagnostics to a file for main.py to read
    const diagnosticsPath = path.join(OUTPUT_DIR, "diagnostics.txt");
    fs.writeFileSync(diagnosticsPath, diagnostics);

    // Return diagnostics for the bug file
    console.log("📋 Diagnostics:", diagnostics.trim());

  } catch (error) {
    console.error("❌ Execution error:", error.message);
    // Ensure output directory exists even on error
    fs.mkdirSync(OUTPUT_DIR, { recursive: true });

    // Write error diagnostics
    const diagnostics = `Execution setup failed: ${error.message}\n`;
    console.log("📋 Error diagnostics:", diagnostics.trim());
  }
})();