// import { chromium } from "playwright";
// import fs from "fs";
// import { buildBlockXML } from "../assembler/xml_builder.js";

// // 1. Build XML (normally from LLM → tree)
// const blockTree = {
//   type: "text_print",
//   value_inputs: {
//     TEXT: {
//       type: "text_literal",
//       fields: {
//         TEXT: "Hello Innogen"
//       }
//     }
//   }
// };

// const xmlBody = buildBlockXML(blockTree);

// const xmlText = `
// <xml xmlns="https://developers.google.com/blockly/xml">
//   ${xmlBody}
// </xml>
// `;

// // 2. Launch browser and execute
// (async () => {
//   const browser = await chromium.launch({ headless: false });
//   const page = await browser.newPage();

//   await page.goto("https://hackpy.tarcin.in/");
//   await page.waitForTimeout(6000); // let Blockly load

//   // 🔥 Inject execute_xml.js into the page
//   await page.addScriptTag({ path: "./execute_xml.js" });

//   // 🔥 Call executeXML INSIDE the browser
//   const result = await page.evaluate(
//     xml => window.executeXML(xml),
//     xmlText
//   );

//   console.log("Execution result:", result);

//   fs.mkdirSync("output", { recursive: true });
//   fs.writeFileSync("output/result.xml", xmlText);
//   fs.writeFileSync("output/result.txt", result.python || "");

//   await browser.close();
// })();

import { chromium } from "playwright";
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

// --------------------
// Resolve paths safely
// --------------------
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const XML_INPUT_PATH = path.resolve(
  __dirname,
  "../assembler/output/program.xml"
);

const EXECUTE_XML_SCRIPT = path.resolve(__dirname, "execute_xml.js");

const OUTPUT_DIR = path.resolve(__dirname, "output");
const RESULT_XML = path.join(OUTPUT_DIR, "result.xml");
const RESULT_TXT = path.join(OUTPUT_DIR, "result.txt");

// --------------------
// Read XML generated by assembler
// --------------------
if (!fs.existsSync(XML_INPUT_PATH)) {
  console.error("❌ program.xml not found. XML assembler may have failed.");
  process.exit(1);
}

const xmlText = fs.readFileSync(XML_INPUT_PATH, "utf-8");

// --------------------
// Execute in Chromium
// --------------------
(async () => {
  const browser = await chromium.launch({ headless: false });
  const page = await browser.newPage();

  await page.goto("https://hackpy.tarcin.in/");
  await page.waitForTimeout(6000); // wait for Blockly to load

  // Inject execute_xml.js into page
  await page.addScriptTag({ path: EXECUTE_XML_SCRIPT });

  // Execute XML inside browser context
  const result = await page.evaluate((xml) => window.executeXML(xml), xmlText);

  // --------------------
  // Save outputs
  // --------------------
  fs.mkdirSync(OUTPUT_DIR, { recursive: true });
  fs.writeFileSync(RESULT_XML, xmlText, "utf-8");
  fs.writeFileSync(RESULT_TXT, result?.python || "", "utf-8");

  console.log("✅ Execution completed");
  console.log("Python output saved:", RESULT_TXT);

  await browser.close();
})();
